"use client";

import { useEffect, useMemo, useState } from "react";

type Tab="movies"|"books"|"products"; type View="discover"|"favourites"; type Feedback="like"|"dislike";
type Item={id:string;type:Tab;title:string;category:string;language:string;creator:string;year:number;rating:number;tags:string[];extra:string;description:string};
type Scored=Item&{score:number;reason:string};
const labels={movies:{singular:"movie",creator:"Director",year:"Released"},books:{singular:"book",creator:"Author",year:"Published"},products:{singular:"product",creator:"Brand",year:"Model year"}};
const moviePosters=["gEU2QniE6E77NI6lCU6MxlNBvIx.jpg","oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg","qJ2tW6WMUDux911r6m7haRef0WH.jpg","7IiTTgloJzvGI1TAYymCfbfl3vT.jpg","39wmItIWsg5sZMyRUHLkWBcuVCM.jpg","p2lVAcPuRPSO8Al6hDDGw0OgMi8.jpg","66A9MqXOyVFCssoloscw79z8Tew.jpg","x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg","eWdyYQreja6JGCzqHWXpWHDrrPo.jpg","gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg","9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg","w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg","gIClWRv5OSe8rl5Koi0AeUcCZ9Z.jpg","3bhkrj58Vtu7enYsRolD1fZdja1.jpg","q719jXXEzOoYaps6babgKnONONX.jpg","hA2ple9q4qnwxp3hKVNhroipsir.jpg","ks0y27y46RkTBqTQV3eZ4gK8P9f.jpg","pThyQovXQrw2m0s9x82twj48Jq4.jpg","n0ybibhJtQ5icDqTp8eRytcIHJx.jpg","7PurMm0gUOJZ8Uk0oyuZlt1CKfJ.jpg","7fn624j5lj3xTme2SgiLCeuedmO.jpg","nEufeZlyAOLqO2brrs0yeF1lgXO.jpg","5BCyeLJHPcRwhu0YaRqUzw00JJ4.jpg","tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg","oTKduWL2tpIKEmkAqF4mFEAWAsv.jpg","f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg","p6tGNs6dY2c0stHOJjUNRr9UEMM.jpg","1QU7HKgsQbGpzsJbJK4pAVQV9F5.jpg","gajva2L0rPYkEWjzgFlBXCAVBE5.jpg","yn5ihODtZ7ofn8pDYfxCmxh8AXI.jpg"];
const bookIsbns=["9780061122415","9780735211292","9780451524935","9780857197689","9780141439518","9780062316097","9780547928227","9780143130727","9781250301697","9780399590504","9781594631931","9781455586691","9780375842207","9780441172719","9780525559474","9780374533557","9780385515993","9780156012195","9780375704024","9780553380163","9781416562603","9780807014295","9780544176560","9789380816289","9780593135204","9781984880963","9780804139298","9780778309451","9780802128256","9781571313560"];
const productPhotos=["photo-1546435770-a3e426bf472b","photo-1592496001020-d31bd830651f","photo-1527814050087-3793815479db","photo-1434494878577-86c23bcb06b9","photo-1561154464-82e9adf32764","photo-1608043152269-423dbba4e7e1","photo-1585515320310-259814833e62","photo-1542291026-7eec264c27ff","photo-1516035069371-29a1b244cc32","photo-1558317374-067fb5f30001","photo-1609091839311-d5365f9ff1c5","photo-1523275335684-37898b6baf30","photo-1505740420928-5e560c06d30e","photo-1587829741301-dc798b83add3","photo-1612196808214-b8e1d6145a8c","photo-1594787318286-3d835c1d207f","photo-1553062407-98eeb64c6a62","photo-1494438639946-1ebd1d20bf85","photo-1527443224154-c4a3942d3acf","photo-1590602847861-f357a9332bbc","photo-1581578731548-c64695cc6952","photo-1601925260368-ae2f83cf8b7f","photo-1502920917128-1aa500764cbd","photo-1484704849700-f032a568e944","photo-1495474472287-4d71bcdd2085","photo-1580480055273-228ff5388ef8","photo-1558002038-1055907df827","photo-1563802560775-4452bb1f4a79","photo-1566576912321-d58ddd7a6088","photo-1593697821252-0c9137d9fc45"];
function imageFor(item:Item){const n=Math.max(0,Number(item.id.slice(1))-1);if(item.type==="movies")return`https://image.tmdb.org/t/p/w500/${moviePosters[n]}`;if(item.type==="books")return`https://covers.openlibrary.org/b/isbn/${bookIsbns[n]}-L.jpg?default=false`;return`https://tse1.mm.bing.net/th?q=${encodeURIComponent(item.title+" official product")}&w=700&h=700&c=7&rs=1&p=0`}
const fallbackImage=(item:Item)=>`https://dummyjson.com/image/700x900/1a201d/d5ff52?text=${encodeURIComponent(item.title)}`;
const tokenize=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g," ").trim().split(/\s+/).filter(x=>x.length>1);
function vector(item:Item,idf:Map<string,number>){const map=new Map<string,number>();const add=(text:string,w:number)=>tokenize(text).forEach(t=>map.set(t,(map.get(t)||0)+w*(idf.get(t)||1)));const w=item.type==="movies"?{category:5,creator:3.5,language:2.4,tags:3.1,extra:2}:item.type==="books"?{category:4.8,creator:4.2,language:2,tags:3.7,extra:1.6}:{category:5.2,creator:4.1,language:.4,tags:3.8,extra:3.1};add(item.category,w.category);add(item.creator,w.creator);add(item.language,w.language);item.tags.forEach(t=>add(t,w.tags));add(item.extra,w.extra);add(item.description,.7);return map}
function cosine(a:Map<string,number>,b:Map<string,number>){let dot=0,aa=0,bb=0;a.forEach((v,k)=>{aa+=v*v;dot+=v*(b.get(k)||0)});b.forEach(v=>bb+=v*v);return aa&&bb?dot/(Math.sqrt(aa)*Math.sqrt(bb)):0}
function buildIdf(items:Item[]){const df=new Map<string,number>();items.forEach(i=>{const words=new Set(tokenize([i.category,i.creator,i.language,...i.tags,i.extra,i.description].join(" ")));words.forEach(w=>df.set(w,(df.get(w)||0)+1))});const idf=new Map<string,number>();df.forEach((n,w)=>idf.set(w,Math.log((items.length+1)/(n+1))+1));return idf}

export default function Home(){
 const[items,setItems]=useState<Item[]>([]),[tab,setTab]=useState<Tab>("movies"),[view,setView]=useState<View>("discover"),[query,setQuery]=useState(""),[category,setCategory]=useState("All"),[sort,setSort]=useState("match"),[feedback,setFeedback]=useState<Record<string,Feedback>>({}),[favourites,setFavourites]=useState<string[]>([]),[recent,setRecent]=useState<string[]>([]),[history,setHistory]=useState<{text:string;time:string}[]>([]),[preferred,setPreferred]=useState<string[]>([]),[theme,setTheme]=useState<"dark"|"light">("dark"),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[profile,setProfile]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[toast,setToast]=useState("");
 useEffect(()=>{fetch("/data/catalog.json").then(r=>r.json()).then(setItems).finally(()=>setTimeout(()=>setLoading(false),550));try{const s=JSON.parse(localStorage.getItem("curio-state")||"null");if(s){setFeedback(s.feedback||{});setFavourites(s.favourites||[]);setRecent(s.recent||[]);setHistory(s.history||[]);setPreferred(s.preferred||[]);setTheme(s.theme||"dark")}}catch{}},[]);
 useEffect(()=>{if(!loading)localStorage.setItem("curio-state",JSON.stringify({feedback,favourites,recent,history,preferred,theme}))},[feedback,favourites,recent,history,preferred,theme,loading]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),1800);return()=>clearTimeout(t)},[toast]);
 const current=useMemo(()=>items.filter(i=>i.type===tab),[items,tab]);const categories=useMemo(()=>["All",...Array.from(new Set(current.map(i=>i.category))).sort()],[current]);
 const scored=useMemo<Scored[]>(()=>{if(!current.length)return[];const idf=buildIdf(current),vecs=new Map(current.map(i=>[i.id,vector(i,idf)]));const liked=current.filter(i=>feedback[i.id]==="like"),disliked=current.filter(i=>feedback[i.id]==="dislike");return current.map(item=>{let sim=0,because="your preferences";if(liked.length){let top=0;liked.forEach(l=>{const s=cosine(vecs.get(item.id)!,vecs.get(l.id)!);sim+=s;if(s>top){top=s;because=l.title}});sim/=liked.length}else sim=.24;const categoryBoost=preferred.includes(item.category)?.24:0;const recentBoost=recent.includes(item.id)?.04:0;const dislikePenalty=disliked.some(d=>cosine(vecs.get(item.id)!,vecs.get(d.id)!)>.35)?.24:0;const own=feedback[item.id]==="like"?.16:feedback[item.id]==="dislike"?-.7:0;const jitter=((item.id.charCodeAt(1)+refresh*7)%11)/300;const score=Math.max(0,Math.min(.98,sim*.62+item.rating/10*.2+categoryBoost+recentBoost+own-dislikePenalty+jitter));const matches=[preferred.includes(item.category)&&item.category,item.tags.find(t=>liked.some(l=>l.tags.includes(t))),liked.some(l=>l.creator===item.creator)&&item.creator].filter(Boolean);return{...item,score,reason:liked.length?`Because you liked ${because}${matches.length?` · shares ${matches[0]}`:""}`:matches.length?`Matches your interest in ${matches[0]}`:`Popular ${item.category.toLowerCase()} pick`}}).filter(i=>feedback[i.id]!=="dislike")},[current,feedback,preferred,recent,refresh]);
 const shown=useMemo(()=>{let list=(view==="favourites"?scored.filter(i=>favourites.includes(i.id)):scored).filter(i=>(category==="All"||i.category===category)&&`${i.title} ${i.creator} ${i.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));return[...list].sort((a,b)=>sort==="rating"?b.rating-a.rating:sort==="newest"?b.year-a.year:sort==="title"?a.title.localeCompare(b.title):b.score-a.score)},[view,scored,favourites,category,query,sort]);
 const recently=recent.map(id=>items.find(i=>i.id===id)).filter(Boolean) as Item[];
 const interact=(item:Item,kind:Feedback)=>{setFeedback(f=>({...f,[item.id]:f[item.id]===kind?undefined!:kind}));setHistory(h=>[{text:`${kind==="like"?"Liked":"Disliked"} ${item.title}`,time:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})},...h].slice(0,24));setToast(kind==="like"?"Preference learned":"We'll show fewer items like this")};
 const open=(item:Item)=>{setRecent(r=>[item.id,...r.filter(x=>x!==item.id)].slice(0,8));setHistory(h=>[{text:`Viewed ${item.title}`,time:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})},...h].slice(0,24));setToast(`${labels[item.type].creator}: ${item.creator}`)};
 const favourite=(id:string)=>{setFavourites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]);setToast(favourites.includes(id)?"Removed from favourites":"Saved to favourites")};
 const changeTab=(t:Tab)=>{setTab(t);setCategory("All");setView("discover");setQuery("");setLoading(true);setTimeout(()=>setLoading(false),380)};
 const refreshAll=()=>{setLoading(true);setRefresh(x=>x+1);setHistory(h=>[{text:`Refreshed ${tab} recommendations`,time:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})},...h].slice(0,24));setTimeout(()=>{setLoading(false);setToast("Recommendations refreshed")},620)};
 const togglePreferred=(c:string)=>setPreferred(p=>p.includes(c)?p.filter(x=>x!==c):[...p,c]);
 return <main className={`app ${theme}`}>
  <header><div className="brand"><div className="brand-mark">C</div><div><strong>CURIO</strong><span>DISCOVER WHAT'S NEXT</span></div></div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles, creators or themes…"/></label><nav><button className={view==="favourites"?"active":""} onClick={()=>setView(view==="favourites"?"discover":"favourites")}>♡ <span>Favourites</span><b>{favourites.length}</b></button><button onClick={()=>setHistoryOpen(true)}>↻ <span>History</span></button><button onClick={()=>setProfile(true)}>◎ <span>Profile</span></button><button className="theme" onClick={()=>setTheme(t=>t==="dark"?"light":"dark")}>{theme==="dark"?"☀":"☾"}</button></nav></header>
  <section className="hero"><div><span className="eyebrow">PERSONALIZED FOR YOU</span><h1>{view==="favourites"?"Your saved collection":"Find your next favourite."}</h1><p>{view==="favourites"?"Everything you saved, in one thoughtful collection.":"Explainable recommendations that learn from every like, view, and preference."}</p></div><div className="hero-stat"><strong>{items.length}</strong><span>LOCAL ITEMS</span></div><div className="hero-stat"><strong>{Object.values(feedback).filter(x=>x==="like").length}</strong><span>LIKES LEARNED</span></div><button className="refresh" onClick={refreshAll}>↻ Refresh recommendations</button></section>
  <div className="content"><div className="tabs">{(["movies","books","products"] as Tab[]).map(t=><button key={t} className={tab===t?"active":""} onClick={()=>changeTab(t)}><i>{t==="movies"?"▶":t==="books"?"▤":"◇"}</i>{t[0].toUpperCase()+t.slice(1)}<span>{items.filter(i=>i.type===t).length}</span></button>)}</div>
  <div className="toolbar"><div className="categories">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><label>Sort by <select value={sort} onChange={e=>setSort(e.target.value)}><option value="match">Best match</option><option value="rating">Highest rated</option><option value="newest">Newest</option><option value="title">A–Z</option></select></label></div>
  {recently.length>0&&view==="discover"&&<section className="recent"><div className="section-head"><div><span>CONTINUE EXPLORING</span><h2>Recently viewed</h2></div><button onClick={()=>setRecent([])}>Clear</button></div><div className="recent-row">{recently.map(i=><button key={i.id} onClick={()=>open(i)}><img src={imageFor(i)} onError={e=>{e.currentTarget.src=fallbackImage(i)}} alt={`${i.title} cover`}/><div><strong>{i.title}</strong><span>{i.category} · ★ {i.rating}</span></div></button>)}</div></section>}
  <section className="recommendations"><div className="section-head"><div><span>{view==="favourites"?"YOUR LIBRARY":"AI-POWERED PICKS"}</span><h2>{view==="favourites"?`${shown.length} saved items`:`Top ${tab} for you`}</h2></div><p>TF-IDF keywords · weighted cosine similarity</p></div>
  {loading?<div className="grid">{Array.from({length:8},(_,i)=><div className="skeleton" key={i}><i/><b/><span/><span/></div>)}</div>:shown.length?<div className="grid">{shown.map(item=><article className="card" key={item.id}><div className={`cover ${item.type}`}><img src={imageFor(item)} onError={e=>{e.currentTarget.src=fallbackImage(item)}} alt={`${item.title} cover`}/><span className="match">{Math.round(item.score*100)}% match</span><button className={favourites.includes(item.id)?"saved":""} onClick={()=>favourite(item.id)} aria-label="Toggle favourite">♥</button><div className="cover-type">{item.category}</div></div><div className="card-body"><div className="meta"><span>★ {item.rating}</span><span>{item.language}</span><span>{item.year}</span></div><h3>{item.title}</h3><p>{item.description}</p><div className="creator"><span>{labels[item.type].creator}</span><strong>{item.creator}</strong></div><div className="tags">{item.tags.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><div className="reason"><i>✦</i><span>{item.reason}</span></div><div className="card-actions"><button onClick={()=>open(item)}>View details</button><button className={feedback[item.id]==="like"?"selected like":""} onClick={()=>interact(item,"like")} aria-label="Like">♡</button><button className={feedback[item.id]==="dislike"?"selected dislike":""} onClick={()=>interact(item,"dislike")} aria-label="Dislike">⌄</button></div></div></article>)}</div>:<div className="empty"><i>◇</i><h3>No matches found</h3><p>Try changing the search, filters, or preferences.</p><button onClick={()=>{setQuery("");setCategory("All")}}>Clear filters</button></div>}
  </section></div>
  <footer><div className="brand"><div className="brand-mark">C</div><div><strong>CURIO</strong><span>LOCAL RECOMMENDATION ENGINE</span></div></div><p>Your preferences stay in this browser · No paid API · Explainable by design</p><span>{items.length} items across 3 collections</span></footer>
  {profile&&<div className="modal-layer" onMouseDown={e=>{if(e.target===e.currentTarget)setProfile(false)}}><section className="modal"><div className="modal-head"><div><span>PERSONALIZATION</span><h2>Profile preferences</h2></div><button onClick={()=>setProfile(false)}>×</button></div><p className="modal-copy">Choose categories you enjoy. Curio combines these with your likes and recent activity.</p><div className="preference-list">{Array.from(new Set(items.map(i=>i.category))).sort().map(c=><button key={c} className={preferred.includes(c)?"selected":""} onClick={()=>togglePreferred(c)}>{preferred.includes(c)?"✓ ":"+ "}{c}</button>)}</div><div className="learning"><div><strong>{preferred.length}</strong><span>interests</span></div><div><strong>{Object.values(feedback).filter(x=>x==="like").length}</strong><span>likes</span></div><div><strong>{recent.length}</strong><span>recent views</span></div></div><button className="modal-primary" onClick={()=>{setProfile(false);refreshAll()}}>Save & refresh recommendations</button></section></div>}
  {historyOpen&&<div className="drawer-layer" onClick={()=>setHistoryOpen(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span>ACTIVITY</span><h2>Recommendation history</h2></div><button onClick={()=>setHistoryOpen(false)}>×</button></div>{history.length?<div className="history-list">{history.map((h,i)=><div key={i}><i>{h.text.startsWith("Liked")?"♡":h.text.startsWith("Viewed")?"◎":"↻"}</i><span>{h.text}</span><time>{h.time}</time></div>)}</div>:<div className="empty small"><i>↻</i><h3>No activity yet</h3></div>}<button className="clear-history" onClick={()=>setHistory([])}>Clear history</button></aside></div>}
  {toast&&<div className="toast">✓ {toast}</div>}
 </main>
}
