"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Cell = "X" | "O" | null; type Symbol = "X" | "O"; type Difficulty = "easy" | "medium" | "hard" | "impossible"; type First = "human" | "ai"; type Theme = "dark" | "light";
type Move = { player: "You" | "AI"; symbol: Symbol; cell: number }; type Stats = { games: number; wins: number; streak: number; bestStreak: number; totalSeconds: number };
const LINES=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]; const EMPTY:Cell[]=Array(9).fill(null); const defaultStats:Stats={games:0,wins:0,streak:0,bestStreak:0,totalSeconds:0};
function result(board:Cell[]){for(const line of LINES){const[a,b,c]=line;if(board[a]&&board[a]===board[b]&&board[a]===board[c])return{winner:board[a] as Symbol,line}}return{winner:null,line:board.every(Boolean)?[]:null}}
function minimax(board:Cell[],turn:Symbol,ai:Symbol,human:Symbol,alpha=-Infinity,beta=Infinity,pruning=false,depth=0):number{const o=result(board);if(o.winner===ai)return 10-depth;if(o.winner===human)return depth-10;if(o.line?.length===0)return 0;const max=turn===ai;let best=max?-Infinity:Infinity;for(let i=0;i<9;i++)if(!board[i]){board[i]=turn;const score=minimax(board,turn==="X"?"O":"X",ai,human,alpha,beta,pruning,depth+1);board[i]=null;if(max){best=Math.max(best,score);alpha=Math.max(alpha,best)}else{best=Math.min(best,score);beta=Math.min(beta,best)}if(pruning&&beta<=alpha)break}return best}
function bestMove(board:Cell[],symbol:Symbol,opponent:Symbol,pruning=true){let best=-Infinity,candidates:number[]=[];for(let i=0;i<9;i++)if(!board[i]){board[i]=symbol;const score=minimax(board,opponent,symbol,opponent,-Infinity,Infinity,pruning);board[i]=null;if(score>best){best=score;candidates=[i]}else if(score===best)candidates.push(i)}return candidates[Math.floor(Math.random()*candidates.length)]}
function chooseAI(board:Cell[],ai:Symbol,human:Symbol,difficulty:Difficulty){const free=board.map((v,i)=>v?-1:i).filter(i=>i>=0);if(difficulty==="easy")return free[Math.floor(Math.random()*free.length)];if(difficulty==="medium"&&Math.random()<.42)return free[Math.floor(Math.random()*free.length)];return bestMove([...board],ai,human,difficulty==="impossible")}
function useSound(enabled:boolean){return useCallback((kind:"click"|"x"|"o"|"win"|"lose"|"draw")=>{if(!enabled)return;try{const AC=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext;const ctx=new AC(),gain=ctx.createGain();gain.connect(ctx.destination);gain.gain.setValueAtTime(.055,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.22);const notes={click:[320],x:[480],o:[330],win:[523,659,784],lose:[330,247],draw:[392,392]}[kind];notes.forEach((freq,index)=>{const osc=ctx.createOscillator();osc.type="sine";osc.frequency.value=freq;osc.connect(gain);osc.start(ctx.currentTime+index*.09);osc.stop(ctx.currentTime+index*.09+.18)});setTimeout(()=>ctx.close(),700)}catch{}},[enabled])}

export default function Home(){
 const[board,setBoard]=useState<Cell[]>(EMPTY),[difficulty,setDifficulty]=useState<Difficulty>("impossible"),[first,setFirst]=useState<First>("human"),[theme,setTheme]=useState<Theme>("dark"),[sound,setSound]=useState(true),[thinking,setThinking]=useState(false),[phase,setPhase]=useState<"playing"|"finished">("playing"),[history,setHistory]=useState<Move[]>([]),[scores,setScores]=useState({human:0,ai:0,draw:0}),[stats,setStats]=useState<Stats>(defaultStats),[hint,setHint]=useState<number|null>(null),[settings,setSettings]=useState(false),[showHistory,setShowHistory]=useState(true),[ready,setReady]=useState(false);const startedAt=useRef(Date.now()),recorded=useRef(false);
 const human:Symbol=first==="human"?"X":"O",ai:Symbol=human==="X"?"O":"X",outcome=useMemo(()=>result(board),[board]),current:Symbol=board.filter(Boolean).length%2===0?"X":"O",playSound=useSound(sound);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem("tactix-settings")||"null");if(s){setDifficulty(s.difficulty||"impossible");setFirst(s.first||"human");setTheme(s.theme||"dark");setSound(s.sound!==false)}const st=JSON.parse(localStorage.getItem("tactix-stats")||"null");if(st)setStats(st)}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("tactix-settings",JSON.stringify({difficulty,first,theme,sound}))},[difficulty,first,theme,sound,ready]);useEffect(()=>{if(ready)localStorage.setItem("tactix-stats",JSON.stringify(stats))},[stats,ready]);
 const finish=useCallback((winner:Symbol|null)=>{if(recorded.current)return;recorded.current=true;setPhase("finished");const seconds=Math.max(1,Math.round((Date.now()-startedAt.current)/1000));if(winner===human){setScores(s=>({...s,human:s.human+1}));setStats(s=>({games:s.games+1,wins:s.wins+1,streak:s.streak+1,bestStreak:Math.max(s.bestStreak,s.streak+1),totalSeconds:s.totalSeconds+seconds}));playSound("win")}else if(winner===ai){setScores(s=>({...s,ai:s.ai+1}));setStats(s=>({...s,games:s.games+1,streak:0,totalSeconds:s.totalSeconds+seconds}));playSound("lose")}else{setScores(s=>({...s,draw:s.draw+1}));setStats(s=>({...s,games:s.games+1,streak:0,totalSeconds:s.totalSeconds+seconds}));playSound("draw")}},[ai,human,playSound]);
 useEffect(()=>{if(phase==="playing"&&(outcome.winner||outcome.line?.length===0))finish(outcome.winner)},[outcome,phase,finish]);
 useEffect(()=>{if(!ready||phase!=="playing"||outcome.line!==null||current!==ai)return;setThinking(true);const timer=setTimeout(()=>{const move=chooseAI([...board],ai,human,difficulty);if(move!==undefined){setBoard(b=>{const n=[...b];n[move]=ai;return n});setHistory(h=>[...h,{player:"AI",symbol:ai,cell:move+1}]);playSound(ai.toLowerCase() as "x"|"o")}setThinking(false)},difficulty==="impossible"?760:560);return()=>{clearTimeout(timer);setThinking(false)}},[ai,board,current,difficulty,human,outcome.line,phase,playSound,ready]);
 const newGame=useCallback(()=>{playSound("click");setBoard([...EMPTY]);setHistory([]);setHint(null);setPhase("playing");recorded.current=false;startedAt.current=Date.now()},[playSound]);
 const place=useCallback((index:number)=>{if(board[index]||thinking||phase!=="playing"||current!==human)return;playSound(human.toLowerCase() as "x"|"o");setHint(null);setBoard(b=>{const n=[...b];n[index]=human;return n});setHistory(h=>[...h,{player:"You",symbol:human,cell:index+1}])},[board,current,human,phase,playSound,thinking]);
 const undo=useCallback(()=>{if(!thinking||history.at(-1)?.player!=="You")return;playSound("click");setBoard(b=>{const n=[...b];const last=history.at(-1)!;n[last.cell-1]=null;return n});setHistory(h=>h.slice(0,-1));setHint(null)},[history,playSound,thinking]);
 const askHint=useCallback(()=>{if(thinking||phase!=="playing"||current!==human)return;setHint(bestMove([...board],human,ai,true));playSound("click");setTimeout(()=>setHint(null),1800)},[ai,board,current,human,phase,playSound,thinking]);
 const changeFirst=(value:First)=>{if(value===first)return;setFirst(value);setBoard([...EMPTY]);setHistory([]);setHint(null);setPhase("playing");recorded.current=false;startedAt.current=Date.now()};
 const resetSettings=()=>{setDifficulty("impossible");setFirst("human");setTheme("dark");setSound(true);setSettings(false);setBoard([...EMPTY]);setHistory([]);setPhase("playing");recorded.current=false;startedAt.current=Date.now()};
 const resetStats=()=>{setScores({human:0,ai:0,draw:0});setStats(defaultStats);playSound("click")};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(/^[1-9]$/.test(e.key))place(Number(e.key)-1);if(e.key.toLowerCase()==="r")newGame();if(e.key.toLowerCase()==="h")askHint();if(e.key.toLowerCase()==="u")undo()};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[askHint,newGame,place,undo]);
 const status=phase==="finished"?outcome.winner===human?"You won!":outcome.winner===ai?"AI wins":"It's a draw":thinking?"AI is thinking…":`${current===human?"Your":"AI"} turn`;const subtitle=phase==="finished"?outcome.winner===human?"Brilliant strategy — well played.":outcome.winner===ai?"The machine found the winning line.":"Perfectly balanced. Try another round.":`You are ${human} · ${difficulty[0].toUpperCase()+difficulty.slice(1)} mode`;const winPct=stats.games?Math.round(stats.wins/stats.games*100):0;
 if(!ready)return <main className="loading">Preparing the arena…</main>;
 return <main className={`app ${theme}`}>
 {phase==="finished"&&outcome.winner===human&&<div className="confetti" aria-hidden>{Array.from({length:26},(_,i)=><i key={i} style={{"--i":i} as React.CSSProperties}/>)}</div>}
 <header><div className="brand"><div className="mark">T</div><div><strong>TACTIX</strong><span>UNBEATABLE AI ARENA</span></div></div><nav><button onClick={()=>setShowHistory(v=>!v)} className={showHistory?"active":""}>History</button><button onClick={()=>setSettings(true)}>Settings</button><button className="theme-button" onClick={()=>setTheme(t=>t==="dark"?"light":"dark")} aria-label="Toggle theme">{theme==="dark"?"☀":"☾"}</button></nav></header>
 <div className="shell"><aside className="left-panel"><section className="panel score-panel"><div className="eyebrow">MATCH SCORE</div><div className="score-grid"><div><span>YOU</span><strong>{scores.human}</strong><small>{human}</small></div><div><span>DRAWS</span><strong>{scores.draw}</strong><small>—</small></div><div><span>AI</span><strong>{scores.ai}</strong><small>{ai}</small></div></div><button className="text-button" onClick={resetStats}>↻ Reset score & stats</button></section>
 <section className="panel controls"><label><span>DIFFICULTY</span><select value={difficulty} onChange={e=>{setDifficulty(e.target.value as Difficulty);newGame()}}><option value="easy">Easy · Random</option><option value="medium">Medium · Tactical</option><option value="hard">Hard · Minimax</option><option value="impossible">Impossible · Alpha-Beta</option></select></label><div className="first"><span>FIRST MOVE</span><div><button className={first==="human"?"selected":""} onClick={()=>changeFirst("human")}>You</button><button className={first==="ai"?"selected":""} onClick={()=>changeFirst("ai")}>AI</button></div></div></section>
 <section className="panel stats"><div className="panel-title"><span>CAREER STATS</span><b>{stats.games} games</b></div><div className="stat-grid"><div><strong>{winPct}%</strong><span>Win rate</span></div><div><strong>{stats.streak}</strong><span>Streak</span></div><div><strong>{stats.bestStreak}</strong><span>Best</span></div><div><strong>{stats.games?Math.round(stats.totalSeconds/stats.games):0}s</strong><span>Avg. time</span></div></div></section></aside>
 <section className="arena"><div className={`status ${thinking?"thinking":""}`}><div className="status-orb">{thinking?<span className="dots"><i/><i/><i/></span>:phase==="finished"?(outcome.winner?"♛":"="):current}</div><div><span>{phase==="finished"?"ROUND COMPLETE":"CURRENT STATUS"}</span><h1>{status}</h1><p>{subtitle}</p></div></div>
 <div className={`board ${phase==="finished"?"complete":""}`}>{board.map((cell,index)=><button key={index} className={`${cell?`filled ${cell.toLowerCase()}`:""} ${outcome.line?.includes(index)?"winner":""} ${hint===index?"hint":""}`} onClick={()=>place(index)} disabled={Boolean(cell)||thinking||phase!=="playing"||current!==human} aria-label={`Cell ${index+1}${cell?`, ${cell}`:""}`}><span>{cell}</span><kbd>{!cell?index+1:""}</kbd></button>)}</div>
 <div className="game-actions"><button className="secondary" onClick={undo} disabled={!thinking||history.at(-1)?.player!=="You"}>↶ Undo <kbd>U</kbd></button><button className="primary" onClick={newGame}>{phase==="finished"?"Play again":"New game"} <span>↻</span></button><button className="secondary" onClick={askHint} disabled={thinking||phase!=="playing"||current!==human}>✦ Hint <kbd>H</kbd></button></div><p className="shortcut">Press <kbd>1–9</kbd> to place · <kbd>R</kbd> to restart</p></section>
 <aside className={`right-panel ${showHistory?"show":""}`}><section className="panel history"><div className="panel-title"><span>MOVE HISTORY</span><b>{history.length}/9</b></div><div className="move-list">{history.length===0?<div className="empty-history"><i>◇</i><p>Your moves will appear here</p></div>:history.map((move,index)=><div className="move" key={index}><b>{index+1}</b><span className={move.symbol.toLowerCase()}>{move.symbol}</span><div><strong>{move.player}</strong><small>Cell {move.cell}</small></div></div>)}</div></section><section className="panel ai-card"><div className="brain">✦</div><div><span>AI ENGINE</span><strong>{difficulty==="impossible"?"Minimax + α–β":difficulty==="hard"?"Full Minimax":difficulty==="medium"?"Mixed strategy":"Random moves"}</strong><small>{difficulty==="impossible"?"Optimal · Unbeatable":"Adaptive game agent"}</small></div><i className="live"/></section></aside></div>
 {settings&&<div className="modal-layer" onMouseDown={e=>{if(e.target===e.currentTarget)setSettings(false)}}><section className="modal"><div className="modal-head"><div><span>GAME PREFERENCES</span><h2>Settings</h2></div><button onClick={()=>setSettings(false)}>×</button></div><div className="setting-row"><div><strong>Appearance</strong><p>Switch between dark and light mode.</p></div><div className="segmented"><button className={theme==="dark"?"selected":""} onClick={()=>setTheme("dark")}>Dark</button><button className={theme==="light"?"selected":""} onClick={()=>setTheme("light")}>Light</button></div></div><div className="setting-row"><div><strong>Sound effects</strong><p>Moves, results, and interface feedback.</p></div><button className={`toggle ${sound?"on":""}`} onClick={()=>setSound(v=>!v)}><i/></button></div><div className="setting-row"><div><strong>Default difficulty</strong><p>Choose the AI used for each new game.</p></div><select value={difficulty} onChange={e=>setDifficulty(e.target.value as Difficulty)}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option><option value="impossible">Impossible</option></select></div><button className="reset-settings" onClick={resetSettings}>Reset settings to defaults</button></section></div>}
 </main>}
